app:
  submission-windows:
    graduating-students:
      from: 2026-01-02
      to: 2026-05-31
    final-grades:
      from: 2026-05-15
      to: 2026-06-20
    exam-grades:
      from: 2026-06-01
      to: 2026-06-30
  dev:
    user:
      username: ${DEV_WEB_USERNAME:dev}
      password: ${DEV_WEB_PASSWORD:devpass}
  maskinporten:
    expected-scope: ${MASKINPORTEN_SCOPE:novari:fakevigoskole}
    test-token:
      value: ${MASKINPORTEN_DEV_TOKEN:local-test-token}
      consumer-org-number: ${MASKINPORTEN_DEV_CONSUMER_ORG_NUMBER:974603268}
      consumer-name: ${MASKINPORTEN_DEV_CONSUMER_NAME:Ås ungdomsskole}
      supplier-org-number: ${MASKINPORTEN_DEV_SUPPLIER_ORG_NUMBER:}
      supplier-name: ${MASKINPORTEN_DEV_SUPPLIER_NAME:}
      delegation-source: ${MASKINPORTEN_DEV_DELEGATION_SOURCE:https://www.altinn.no}
