spring:
  security:
    oauth2:
      client:
        provider:
          idporten:
            authorization-uri: ${IDPORTEN_AUTHORIZATION_URI:https://login.test.idporten.no/authorize}
            token-uri: ${IDPORTEN_TOKEN_URI:https://test.idporten.no/token}
            user-info-uri: ${IDPORTEN_USERINFO_URI:https://test.idporten.no/userinfo}
            jwk-set-uri: ${IDPORTEN_JWK_SET_URI:https://test.idporten.no/jwks.json}
      resourceserver:
        jwt:
          jwk-set-uri: ${MASKINPORTEN_JWK_SET_URI:https://test.maskinporten.no/jwk}

app:
  submission-windows:
    graduating-students:
      from: 2026-01-02
      to: 2026-05-31
    final-grades:
      from: 2026-05-15
      to: 2026-06-20
    exam-grades:
      from: 2026-06-01
      to: 2026-06-30
